### ISSUE TITLE
Test on as many plattforms and devices as possible

### ISSUE THREAD

**Issue by konstin** [konstin/stk-wiki-theme#17] opened 2015-08-29 22:16 UTC
@samuncle @hiker @auriamg It would be great if you could test how good the skin works on your devices and tell me what works and what doesn't work. Especially Internet Explorer and mobile browsers would be interesting because they often cause problems. Any other feedback is of course also welcome.

**Comment by MatthewsSam** [comment] 2015-08-30 00:01
It seems the download section should be a bit improved (similar to what we have now). We also have to take into consideration special pages (with "different css") like:

http://supertuxkart.sourceforge.net/Get_involved
http://supertuxkart.sourceforge.net/Discover

**Comment by konstin** [comment] 2015-08-30 07:47
This is still on the todo list (#13), but the skin itself should work properly before creating content based on that skin.

**Comment by auriamg** [comment] 2015-08-30 23:55
konstin : while this looks nice a great start, the issue is that it's very hard to properly evaluate the skin without content :) Probably a little content should be copied over to demonstrate the skin better, atm it's just hard to tell. Also some of the pages, like Community, appear quite broken. This page should be fixed first I guess?

One thing I note, some links are blue (or red when visited), we should probably sin them to be green, or some other color that matches our theme

There also doesn't seem to be a lot of visible different between h1 and h2 captions, maybe this can be improved

PS: the url is https://utasart.gienah.uberspace.de/wiki/Main_Page you forgot to mention it

**Closed as completed** 2016-08-10 22:49 UTC
Labels: help wanted
